### ISSUE TITLE
What happened to the module on /x?

### ISSUE THREAD

**Issue by KnorpelSenf** [supabase-community/deno-supabase-js#1]
https://deno.land/x/supabase/mod.ts used to be a thing, but now there is a new major version that simply removed all files. The repo changed to this repo. Can you explain what happened here?

Also, why are we supposed to use the less trusted esm.sh over deno.land/x?

**Comment by thorwebdev** [comment]
@KnorpelSenf sorry for the confusion, the module on deno.land was an unofficial and eventually unmaintained fork. Therefore the advise to use the main repo published to npm. We now also release to JSR, so we've updated the guidance to that. Hope this helps and sorry for the delay!
